name = "Kraken"
version = "0.1.0"
defaultTargets = ["Kraken"]

[[lean_lib]]
name = "Kraken"

[[lean_exe]]
name = "krakentest"
root = "KrakenTest"

[[lean_exe]]
name = "mkcinsertionsorttest"
root = "Kraken.CTests.MkInsertionsortTest"
